# <center>World Map Geovisualization using Folium and Covid Data

### <center>Instructor: Vinita Silaparasetty

### Import Libraries

In [1]:
import json
import folium
import requests
import mimetypes
import http.client
import pandas as pd
from folium.plugins import HeatMap
from pandas.io.json import json_normalize

### Generate Base Map

### Access Data via API

In [2]:
conn=http.client.HTTPSConnection("api.covid19api.com")
payload=''
headers={}
conn.request("GET","/summary",payload,headers)
res=conn.getresponse()
data=res.read().decode('UTF-8')

### Convert Data to JSON

In [3]:
covid1=json.loads(data)

### Normalize Data

In [4]:
json_normalize(covid1['Countries'],sep=",")

,Country,CountryCode,Slug,NewConfirmed,TotalConfirmed,NewDeaths,TotalDeaths,NewRecovered,TotalRecovered,Date
0,Afghanistan,AF,afghanistan,30,39074,3,1444,0,32576,2020-09-22T12:57:28Z
1,Albania,AL,albania,150,12535,2,364,55,6995,2020-09-22T12:57:28Z
2,Algeria,DZ,algeria,197,50023,7,1679,133,35180,2020-09-22T12:57:28Z
3,Andorra,AD,andorra,117,1681,0,53,35,1199,2020-09-22T12:57:28Z
4,Angola,AO,angola,126,4117,2,154,4,1449,2020-09-22T12:57:28Z
...,...,...,...,...,...,...,...,...,...,...
183,Viet Nam,VN,vietnam,0,1068,0,35,5,947,2020-09-22T12:57:28Z
184,Western Sahara,EH,western-sahara,0,10,0,1,0,8,2020-09-22T12:57:28Z
185,Yemen,YE,yemen,2,2028,0,586,8,1235,2020-09-22T12:57:28Z
186,Zambia,ZM,zambia,44,14175,1,331,264,13629,2020-09-22T12:57:28Z
187,Zimbabwe,ZW,zimbabwe,0,7683,0,225,0,5924,2020-09-22T12:57:28Z

### Convert to Pandas DataFrame

In [5]:
df=pd.DataFrame(covid1['Countries'])
df

,Country,CountryCode,Slug,NewConfirmed,TotalConfirmed,NewDeaths,TotalDeaths,NewRecovered,TotalRecovered,Date,Premium
0,Afghanistan,AF,afghanistan,30,39074,3,1444,0,32576,2020-09-22T12:57:28Z,{}
1,Albania,AL,albania,150,12535,2,364,55,6995,2020-09-22T12:57:28Z,{}
2,Algeria,DZ,algeria,197,50023,7,1679,133,35180,2020-09-22T12:57:28Z,{}
3,Andorra,AD,andorra,117,1681,0,53,35,1199,2020-09-22T12:57:28Z,{}
4,Angola,AO,angola,126,4117,2,154,4,1449,2020-09-22T12:57:28Z,{}
...,...,...,...,...,...,...,...,...,...,...,...
183,Viet Nam,VN,vietnam,0,1068,0,35,5,947,2020-09-22T12:57:28Z,{}
184,Western Sahara,EH,western-sahara,0,10,0,1,0,8,2020-09-22T12:57:28Z,{}
185,Yemen,YE,yemen,2,2028,0,586,8,1235,2020-09-22T12:57:28Z,{}
186,Zambia,ZM,zambia,44,14175,1,331,264,13629,2020-09-22T12:57:28Z,{}
187,Zimbabwe,ZW,zimbabwe,0,7683,0,225,0,5924,2020-09-22T12:57:28Z,{}

### Drop Unnecessary Columns

In [6]:
covid2=df.drop(columns=['CountryCode','Slug','Date','Premium'],axis=1)
covid2

,Country,NewConfirmed,TotalConfirmed,NewDeaths,TotalDeaths,NewRecovered,TotalRecovered
0,Afghanistan,30,39074,3,1444,0,32576
1,Albania,150,12535,2,364,55,6995
2,Algeria,197,50023,7,1679,133,35180
3,Andorra,117,1681,0,53,35,1199
4,Angola,126,4117,2,154,4,1449
...,...,...,...,...,...,...,...
183,Viet Nam,0,1068,0,35,5,947
184,Western Sahara,0,10,0,1,0,8
185,Yemen,2,2028,0,586,8,1235
186,Zambia,44,14175,1,331,264,13629
187,Zimbabwe,0,7683,0,225,0,5924

### Generate Base Map

In [7]:
m=folium.Map(tiles="Stamen Terrain",min_zoom=1.5)
m

### Obtain Geodata

geodata url: https://raw.githubusercontent.com/python-visualization/folium/master/examples/data

geo data file: world-countries.json

In [8]:
url='https://raw.githubusercontent.com/python-visualization/folium/master/examples/data'
country_shapes=f'{url}/world_countries.json'

### Generate Choropleth Map Layer

In [9]:
folium.Choropleth(geo_data=country_shapes, min_zoom=2, 
                 name='Covid-19', data=covid2, 
                 columns=['Country','TotalConfirmed'],
                 key_on='feature.properties.name',
                 fill_color='OrRd', nan_fill_color='black', 
                 legend_name='Total Confirmed Covid Cases'
                 ).add_to(m)#Adding choropleth map to base map
m

AttributeError: module 'folium' has no attribute 'Choropleth'

### Generate Circular Markers

In [10]:
covid2.update(covid2['TotalConfirmed'].map('Total Confirmed:{}'.format))
covid2.update(covid2['TotalRecovered'].map('Total Recovered:{}'.format))

coordinates of countries: https://raw.githubusercontent.com/VinitaSilaparasetty/covid-map/master/country-coordinates-world.csv

In [11]:
coordinates=pd.read_csv('https://raw.githubusercontent.com/VinitaSilaparasetty/covid-map/master/country-coordinates-world.csv')
coordinates

      latitude   longitude            Country
0    33.939110   67.709953        Afghanistan
1    41.153332   20.168331            Albania
2    28.033886    1.659626            Algeria
3   -14.270972 -170.132217     American Samoa
4    42.546245    1.601554            Andorra
..         ...         ...                ...
239 -13.768752 -177.156097  Wallis and Futuna
240  24.215527  -12.885834     Western Sahara
241  15.552727   48.516388              Yemen
242 -13.133897   27.849332             Zambia
243 -19.015438   29.154857           Zimbabwe

[244 rows x 3 columns]

In [12]:
covid_final=pd.merge(covid2,coordinates,on='Country')

In [13]:
def plotDot(point):
    folium.CircleMarker(location=[point.latitude,point.longitude],
                       radius=5,
                       weight=2,
                       popup=[point.Country,point.TotalConfirmed,point.TotalRecovered],
                       fill_color='#000000').add_to(m)#add markers to choropleth map

In [14]:
covid_final.apply(plotDot,axis=1)
m.fit_bounds(m.get_bounds())
m

AttributeError: ("'list' object has no attribute 'get_name'", 'occurred at index 0')

### Generate Base Map

In [15]:
m1=folium.Map(tiles='StamenToner',min_zoom=2)
m1

### Generate Heat Map Layer

In [ ]:
deaths=covid_final['TotalDeaths'].astype(float)

In [ ]:
lat=covid_final['latitude'].astype(float)

In [ ]:
lon=covid_final['longitude'].astype(float)

In [ ]:
m1.add_child(HeatMap(zip(lat,long,deaths),radius=0))

### Generate Circular Marker

In [ ]:
def plotDot(point):
    folium.CircleMarker(location=[point.latitude,point.longitude],
                       radius=5,
                       weight=2,
                       popup=[point.Country,point.TotalDeaths],
                       fill_color='#000000').add_to(m1)
covid_final.apply(plotDot,axis=1)
m1.fit_bounds(m1.get_bounds())
m1